name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: 'gh-pages'
      - name: Cleanup
        run: rm -rf -v !("CNAME"|"rawdata")
        working-directory: gh-pages
      - name: Copy build over
        run: cp -r build/* gh-pages
      - name: Add 404
        run: cp index.html 404.html
        working-directory: gh-pages
      - name: Push
        run: |
          git config --global user.name 'Bot'
          git config --global user.email 'bot@users.noreply.github.com'
          git add .
          git commit -am "Deploy"
          git push
